proxmox_node: prox
template_name:  openSuse-Leap-15.6-cloudinit-template

vmid: 105
vm_name: node-exporter-01

#vm_ip: 
#vm_cidr: 
#vm_gateway: X.x.x.x
vm_dns: 1.1.1.1

storage: local-zfs
ssh_user: test_1
